<?php

/**
* @var $block \Magelearn\CashDate\Block\Info\Cashondelivery
*/
?>
<?= $block->escapeHtml($block->getMethod()->getTitle()) ?>
<?php if ($block->getInstructions()) : ?>
    <table>
        <tbody>
            <tr>
                <td>
                	<?= /* @noEscape */ nl2br($block->escapeHtml($block->getInstructions())) ?>
                	<?php if ($block->getCashDate()): ?>
					    <br /><?= $block->escapeHtml(__('Checkout Date: ')) ?>
					    <?= $block->escapeHtml($block->getCashDate()) ?>
					<?php endif; ?>
                </td>
            </tr>
        </tbody>
    </table>
<?php endif; ?>
