<?php
/**
 * @var $block \Magelearn\CashDate\Block\Info\Cashondelivery
 */
?>
<?= $block->escapeHtml($block->getMethod()->getTitle()) ?>{{pdf_row_separator}}
<?php if ($block->getCashDate()): ?>
    <?= $block->escapeHtml(__('Checkout Date: ')) ?>
    <?= $block->escapeHtml($block->getCashDate()) ?>
    {{pdf_row_separator}}
<?php endif; ?>
<?php if ($block->getInstructions()): ?>
	<?= /* @noEscape */ nl2br($block->escapeHtml($block->getInstructions())) ?>
	{{pdf_row_separator}}
<?php endif; ?>
<?php if ($specificInfo = $block->getSpecificInformation()) : ?>
    <?php foreach ($specificInfo as $label => $value) : ?>
        <?= $block->escapeHtml($label) ?>:
        <?= $block->escapeHtml(implode(' ', $block->getValueAsArray($value))) ?>
        {{pdf_row_separator}}
    <?php endforeach; ?>
<?php endif;?>

<?= $block->escapeHtml(implode('{{pdf_row_separator}}', $block->getChildPdfAsArray())) ?>